title:  Pavithra Willingiri
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A dedicated analyst with a passion for exploring data ,Proficient in SQL, Python, and Power BI, with a validated competence to automate dashboards, streamline processes, and provide tactical direction to stakeholders using easy-to-understand language. Skilled in analyzing behavioral data, identifying business gaps, and developing solutions that meet the needs of both internal and external stakeholders.
  <br><br>
  <br><br>
  <br><br>
  <br>
  <a href="https://www.linkedin.com/in/pavithra-willingiri-995a2458/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.notion.so/pavithrawillingiri/Pavithra-Willingiri-75bf29fe75de4e2f94163a1146a7fed9">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
